### ISSUE TITLE
Cycle break

### ISSUE THREAD

**Issue by IanaKhitsko** [daisy-ua/euro-diffusion#3]
https://github.com/daisy-ua/euro-diffusion/blob/3d1b458af58e3b4996da1eded2f853b6f4727120/app/src/main/java/eurodiffusion/source/EuropeMap.kt#L44

can you break the internal cycle in this place? There is no sense to check for completion anymore

**Comment by daisy-ua** [comment]
The loop must iterate over each country in order to update the number of days required to complete
