### ISSUE TITLE
Mutable

### ISSUE THREAD

**Issue by IanaKhitsko** [daisy-ua/euro-diffusion#4]
https://github.com/daisy-ua/euro-diffusion/blob/3d1b458af58e3b4996da1eded2f853b6f4727120/app/src/main/java/eurodiffusion/source/City.kt#L12

Just wondering - why do you use mutable map and list here?

**Comment by daisy-ua** [comment]
Mutable* is a collection that can be modified (e.g. supports adding and removing elements)
