### ISSUE TITLE
motifCount

### ISSUE THREAD

**Issue by IanaKhitsko** [daisy-ua/euro-diffusion#5]
https://github.com/daisy-ua/euro-diffusion/blob/3d1b458af58e3b4996da1eded2f853b6f4727120/app/src/main/java/eurodiffusion/source/City.kt#L8

Where the motifCount is set? It is a private property, but I can't find any setter for it

**Comment by daisy-ua** [comment]
It is passed via constructor during europe map creation

https://github.com/daisy-ua/euro-diffusion/blob/3d1b458af58e3b4996da1eded2f853b6f4727120/app/src/main/java/eurodiffusion/source/EuropeMap.kt#L59
